[package]
name = "mdp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_float_eq = "1.1.3"
itertools = "0.10.5"
rand = "0.8.5"
rand_chacha = "0.3.1"
